version: "3.8"

services:
  hoddb:
    container_name: trdk02_ed_hoddb
    image: gtfierro/hod:0.6.1
    ports:
      - "47808:47808"
    expose:
      - "47808"
    volumes:
      - ./database/hoddb/:/etc/hod/
  mongodb:
    container_name: trdk02_ed_mongodb
    image: mongo:4.4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "27018:27017"
    expose:
      - "27018"
    volumes:
      - ./database/mongodb/seed/:/seed/
      - ./database/mongodb/mongod.conf:/etc/mongod.conf
      - ./database/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - trdk02-mongodb:/data/db/
    command: ["-f", "/etc/mongod.conf"]
  backend:
    container_name: trdk02_ed_backend
    build:
      context: ./backend/
      dockerfile: config/Dockerfile
    depends_on:
      - mongodb
      - hoddb
    environment:
      - BRICK_HOST=hoddb # Same as the hoddb service name
      - BRICK_PORT=47808 # Same as the hoddb service port
      - DB_HOST=mongodb # Same as the mongodb service name
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./backend/:/srv/app/
      - /srv/app/node_modules
    command: npm run dev
  frontend:
    container_name: trkd02_ed_frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on: 
      - backend
    environment: 
      - REACT_APP_API_URI=backend # Same as the backend service name
    ports:
      - "80:3000"
    expose:
      - "80"
    volumes:
      - ./frontend/:/srv/app/

volumes:
  trdk02-mongodb:
