### HodDB Configuration
# commented out lines are default configuration options

####
# Location and structure of database
####

Buildings:
  miniAasheim: /etc/hod/buildings/miniAasheim.ttl
  miniTille: /etc/hod/buildings/miniTiller.ttl

# the location of the database files
DBPath: _hoddb

# list of links to ontology files to load before each building
Ontologies:
  - "/etc/hod/Brick.ttl"

EnableHTTP: true
LogLevel: Debug

ServerPort: 47808
ListenAddress: 0.0.0.0
