###
# This CI is only run if there are changes on the frontend application
# It will perform linting and matrix testing
###

name: Frontend CI

on:
  pull_request:
    paths:
    - 'frontend/**'

defaults:
  run:
    working-directory: ./frontend

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

  test: 
    runs-on: ubuntu-latest

    needs: lint

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Nodejs v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Test
        run: npm test
