# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  frontend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Nodejs v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        working-directory: ./frontend
        run: npm install
      
      - name: lint
        working-directory: ./frontend
        run: npm run lint

      - name: test
        working-directory: ./frontend
        run: npm test

  backend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Nodejs v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Runs a single command using the runners shell
      - name: install
        working-directory: ./backend
        run: npm install

       - name: lint
        working-directory: ./backend
        run: npm run lint

      - name: test
        working-directory: ./backend
        run: npm test
